version: "3.7"

volumes:
  db-data:

services:
  vote:
    image: schoolofdevops/vote
    ports:
      - 5000:80
    depends_on:
      - redis

  redis:
    image: redis:alpine

  worker:
    image: schoolofdevops/vote-worker
    depends_on:
      - redis

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data

  result:
    image:   myselfakshatha/vote
    ports:
      - 5001:80

